### ISSUE TITLE
Write a MINE Enterprise project description

### ISSUE THREAD

**Issue by Johnsgeo0** [mtu-pstdl/website#31]
Lunabotics Rover and updated renders, Website Link

**Comment by Johnsgeo0** [comment]
![IMG_9498](https://user-images.githubusercontent.com/69485852/106295463-7b2cb300-621e-11eb-9f27-1f21463eb335.jpg)
![IMG_9499](https://user-images.githubusercontent.com/69485852/106295482-7ec03a00-621e-11eb-9fe7-f9a1232b2151.jpg)

**Comment by Johnsgeo0** [comment]
![Astro Huskies Logo](https://user-images.githubusercontent.com/69485852/106295753-d199f180-621e-11eb-9ba4-af118c14926a.png)
![MINE Logo](https://user-images.githubusercontent.com/69485852/106295795-e1193a80-621e-11eb-812b-3be1118c0489.JPG)

**Comment by Johnsgeo0** [comment]
![Uploading Team Photo.JPG…]()

**Comment by Johnsgeo0** [comment]
![Subsea ROV Render](https://user-images.githubusercontent.com/69485852/106297664-f1cab000-6220-11eb-8b26-9fe5c43a14e8.png)

**Comment by Johnsgeo0** [comment]
The Mining Innovation Enterprise is a multi-discipline organization of undergraduate students from Michigan Technological University. This enterprise focuses on innovative methods of excavation and mining techniques. Everything from deep-sea mining on earth, to mining for minerals and water on the moon and Mars. Utilizing the resources of the PSTDL, this enterprise team continues to work on several interesting projects such as the development of a Subsea ROV designed to mine nodule deposits on the seafloor, developing and testing a methodology to extract water from Gypsum rock for NASA, building a lunar excavation robot to compete in NASA’s Lunabotics competition, and the construction of a field rover capable of handling interchangeable payloads for different field tests.
To learn more about the Mining Innovation Enterprise and its current projects, visit http://mine.geo.mtu.edu/

**Comment by Johnsgeo0** [comment]
@elijahjcobb Here is a quick write up for the Mining Innovation Enterprise. Let me know if you'd like more information/descriptions for each of the projects.

**Comment by elijahjcobb** [comment]
@Johnsgeo0, will do!
